export const STRINGS = {
  APP_NAME: 'CSS Motion Master',
  APP_TAGLINE: 'Professional Animation Studio',

  NAV_HOME: 'Home',
  NAV_FAVORITES: 'Favorites',
  NAV_PLAYLISTS: 'Playlists',
  NAV_COMPARE: 'Compare',
  NAV_BUILDER: 'Builder',
  NAV_ANALYTICS: 'Analytics',
  NAV_DOCS: 'Docs',
  NAV_SETTINGS: 'Settings',

  SEARCH_PLACEHOLDER: 'Search animations...',
  SEARCH_EMPTY_TITLE: 'No results found',
  SEARCH_EMPTY_SUBTITLE: 'Try adjusting your search or filters',
  SEARCH_CLEAR: 'Clear search',

  FILTER_PANEL_TITLE: 'Filters',
  FILTER_RESET: 'Reset all filters',
  FILTER_CATEGORIES: 'Categories',
  FILTER_TAGS: 'Tags',
  FILTER_BROWSER: 'Browser Support',
  FILTER_TRIGGER: 'Trigger Type',
  FILTER_COMPLEXITY: 'Complexity',
  FILTER_PERFORMANCE: 'Performance Score',
  FILTER_HAS_JS: 'Has JavaScript',
  FILTER_ACTIVE_COUNT: 'active filter',
  FILTER_ACTIVE_COUNT_PLURAL: 'active filters',

  SORT_LABEL: 'Sort',
  SORT_NAME_AZ: 'Name A-Z',
  SORT_NAME_ZA: 'Name Z-A',
  SORT_NEWEST: 'Newest',
  SORT_OLDEST: 'Oldest',
  SORT_MOST_VIEWED: 'Most Viewed',
  SORT_MOST_COPIED: 'Most Copied',
  SORT_MOST_DOWNLOADED: 'Most Downloaded',
  SORT_PERFORMANCE: 'Performance Score',
  SORT_COMPLEXITY: 'Complexity Score',

  LAYOUT_COMFORTABLE: 'Comfortable',
  LAYOUT_COMPACT: 'Compact',
  LAYOUT_LIST: 'List',

  CARD_ADD_TO_COMPARE: 'Add to Compare',
  CARD_ADD_TO_PLAYLIST: 'Add to Playlist',
  CARD_COPY_CSS: 'Copy CSS',
  CARD_COPY_SUCCESS: 'CSS copied to clipboard',
  CARD_DOWNLOAD: 'Download',
  CARD_DOWNLOAD_SUCCESS: 'Animation downloaded',
  CARD_FAVORITE_ADD: 'Added to favorites',
  CARD_FAVORITE_REMOVE: 'Removed from favorites',
  CARD_VIEW_DETAILS: 'View Details',
  CARD_STAGGER_PREVIEW: 'Stagger Preview',

  DETAIL_OPEN_FULL: 'Open full page',
  DETAIL_SHARE: 'Share',
  DETAIL_SHARE_SUCCESS: 'Link copied to clipboard',
  DETAIL_VARIANTS: 'Variants',
  DETAIL_RELATED: 'Related Animations',
  DETAIL_YOU_MAY_LIKE: 'You might also like',
  DETAIL_PERFORMANCE: 'Performance',
  DETAIL_PROPERTIES: 'Animated Properties',

  CODE_TAB_CSS: 'CSS',
  CODE_TAB_HTML: 'HTML',
  CODE_TAB_JS: 'JavaScript',
  CODE_TAB_FULL: 'Full Page',
  CODE_TAB_REACT: 'React Component',
  CODE_TAB_VUE: 'Vue Component',
  CODE_COPY: 'Copy',
  CODE_DOWNLOAD: 'Download',
  CODE_COPY_SUCCESS: 'Code copied',

  PLAYBACK_PLAY: 'Play',
  PLAYBACK_PAUSE: 'Pause',
  PLAYBACK_RESTART: 'Restart',
  PLAYBACK_STEP_FORWARD: 'Step Forward',
  PLAYBACK_STEP_BACK: 'Step Back',
  PLAYBACK_SPEED: 'Speed',
  PLAYBACK_DURATION: 'Duration',
  PLAYBACK_EASING: 'Easing',
  PLAYBACK_ITERATIONS: 'Iterations',
  PLAYBACK_DIRECTION: 'Direction',
  PLAYBACK_FILL: 'Fill Mode',
  PLAYBACK_DELAY: 'Delay',
  PLAYBACK_END_DELAY: 'End Delay',
  PLAYBACK_INFINITE: 'Infinite',

  FAVORITES_TITLE: 'Favorites',
  FAVORITES_EMPTY_TITLE: 'No favorites yet',
  FAVORITES_EMPTY_SUBTITLE: 'Star animations to add them here',
  FAVORITES_EXPORT: 'Export Favorites',
  FAVORITES_IMPORT: 'Import Favorites',
  FAVORITES_EXPORT_SUCCESS: 'Favorites exported',
  FAVORITES_IMPORT_SUCCESS: 'Favorites imported',

  HISTORY_TITLE: 'Recently Viewed',
  HISTORY_CLEAR: 'Clear History',
  HISTORY_CLEAR_CONFIRM: 'History cleared',
  HISTORY_EMPTY: 'No history yet',

  PLAYLISTS_TITLE: 'Playlists',
  PLAYLISTS_CREATE: 'New Playlist',
  PLAYLISTS_CREATE_PLACEHOLDER: 'Playlist name',
  PLAYLISTS_CREATE_SUCCESS: 'Playlist created',
  PLAYLISTS_DELETE_CONFIRM: 'Delete playlist?',
  PLAYLISTS_DELETE_SUCCESS: 'Playlist deleted',
  PLAYLISTS_RENAME_SUCCESS: 'Playlist renamed',
  PLAYLISTS_EMPTY_TITLE: 'No playlists yet',
  PLAYLISTS_EMPTY_SUBTITLE: 'Create a playlist to organize animations',
  PLAYLISTS_ADD_ANIMATION: 'Added to playlist',
  PLAYLISTS_REMOVE_ANIMATION: 'Removed from playlist',
  PLAYLISTS_PLAY_ALL: 'Play All',
  PLAYLISTS_SHARE: 'Share Playlist',
  PLAYLISTS_SHARE_SUCCESS: 'Playlist link copied',

  COMPARE_TITLE: 'Compare Animations',
  COMPARE_EMPTY_TITLE: 'Nothing to compare yet',
  COMPARE_EMPTY_SUBTITLE: 'Add animations to the compare tray from any card',
  COMPARE_ADD: 'Add to Compare',
  COMPARE_REMOVE: 'Remove',
  COMPARE_CLEAR: 'Clear All',
  COMPARE_MERGE: 'Download Merged CSS',
  COMPARE_LIMIT: 'Compare limit reached (max 4)',

  BUILDER_TITLE: 'Animation Builder',
  BUILDER_ELEMENT: 'Element',
  BUILDER_KEYFRAMES: 'Keyframe Stops',
  BUILDER_ADD_STOP: 'Add Stop',
  BUILDER_REMOVE_STOP: 'Remove Stop',
  BUILDER_ANIMATION_NAME: 'Animation Name',
  BUILDER_SAVE: 'Save to Library',
  BUILDER_SAVE_SUCCESS: 'Animation saved to library',
  BUILDER_EXPORT_CSS: 'Export CSS',
  BUILDER_COPY_CSS: 'Copy CSS',

  CUSTOMIZER_TITLE: 'CSS Variables',
  CUSTOMIZER_COLORS: 'Colors',
  CUSTOMIZER_SLIDERS: 'Adjustments',
  CUSTOMIZER_PRESETS: 'Presets',
  CUSTOMIZER_SAVE_PRESET: 'Save as Preset',
  CUSTOMIZER_EXPORT_THEME: 'Export Theme',
  CUSTOMIZER_RESET: 'Reset to Defaults',
  CUSTOMIZER_RESET_SUCCESS: 'Theme reset to defaults',
  CUSTOMIZER_PRESET_SAVED: 'Preset saved',
  CUSTOMIZER_THEME_EXPORTED: 'Theme exported as theme.css',

  ANALYTICS_TITLE: 'Analytics Dashboard',
  ANALYTICS_TOP_VIEWED: 'Top 10 Most Viewed',
  ANALYTICS_COPY_EVENTS: 'Copy Events (Last 14 Days)',
  ANALYTICS_TAB_DISTRIBUTION: 'Copy Tab Distribution',
  ANALYTICS_SESSION_TIME: 'Total Session Time',
  ANALYTICS_EXPORT: 'Export Analytics',
  ANALYTICS_CLEAR: 'Clear Analytics',
  ANALYTICS_CLEAR_CONFIRM: 'Analytics cleared',
  ANALYTICS_SESSIONS: 'Sessions',

  DOCS_TITLE: 'Documentation',
  DOCS_EMPTY: 'Documentation not found',

  SETTINGS_TITLE: 'Settings',
  SETTINGS_APPEARANCE: 'Appearance',
  SETTINGS_PLAYBACK: 'Playback',
  SETTINGS_PERFORMANCE: 'Performance',
  SETTINGS_GRID: 'Grid',
  SETTINGS_DATA: 'Data',
  SETTINGS_THEME: 'Theme',
  SETTINGS_THEME_DARK: 'Dark',
  SETTINGS_THEME_LIGHT: 'Light',
  SETTINGS_ACCENT: 'Accent Color',
  SETTINGS_FONT_SIZE: 'Base Font Size',
  SETTINGS_DEFAULT_SPEED: 'Default Speed',
  SETTINGS_AUTO_PLAY: 'Auto-Play Previews',
  SETTINGS_REDUCED_MOTION: 'Reduced Motion',
  SETTINGS_PREVIEW_QUALITY: 'Preview Quality',
  SETTINGS_QUALITY_HIGH: 'High',
  SETTINGS_QUALITY_MEDIUM: 'Medium',
  SETTINGS_QUALITY_STATIC: 'Static',
  SETTINGS_DEFAULT_LAYOUT: 'Default Layout',
  SETTINGS_DEFAULT_SORT: 'Default Sort',
  SETTINGS_GRID_DENSITY: 'Grid Density',
  SETTINGS_EXPORT_DATA: 'Export All Data',
  SETTINGS_IMPORT_DATA: 'Import Data',
  SETTINGS_RESET_DATA: 'Reset All Data',
  SETTINGS_RESET_CONFIRM: 'All data has been reset',
  SETTINGS_EXPORT_SUCCESS: 'Data exported',
  SETTINGS_IMPORT_SUCCESS: 'Data imported',

  SLIDESHOW_PREV: 'Previous',
  SLIDESHOW_NEXT: 'Next',
  SLIDESHOW_PAUSE: 'Pause',
  SLIDESHOW_PLAY: 'Play',
  SLIDESHOW_EXIT: 'Exit',
  SLIDESHOW_DWELL: 'Time per animation',

  NOTIFICATION_COPY_SUCCESS: 'Copied to clipboard',
  NOTIFICATION_DOWNLOAD_SUCCESS: 'Download started',
  NOTIFICATION_ERROR: 'Something went wrong',
  NOTIFICATION_OFFLINE: 'You are offline',
  NOTIFICATION_BACK_ONLINE: 'Back online',
  NOTIFICATION_INSTALL_PROMPT: 'Install CSS Motion Master as an app',
  NOTIFICATION_INSTALL_BTN: 'Install',

  IMPORT_TITLE: 'Import CSS Animation',
  IMPORT_PLACEHOLDER: 'Paste @keyframes CSS here...',
  IMPORT_SUBMIT: 'Import Animation',
  IMPORT_SUCCESS: 'Animation imported successfully',
  IMPORT_ERROR: 'Failed to parse CSS. Make sure it contains valid @keyframes.',

  EXPORT_BUNDLE_TITLE: 'Export Bundle',
  EXPORT_BUNDLE_SELECT_ALL: 'Select All',
  EXPORT_BUNDLE_DESELECT: 'Deselect All',
  EXPORT_BUNDLE_DOWNLOAD: 'Download Bundle',
  EXPORT_BUNDLE_SUCCESS: 'Bundle downloaded',
  EXPORT_BUNDLE_EMPTY: 'Select at least one animation',

  NOT_FOUND_TITLE: '404',
  NOT_FOUND_SUBTITLE: 'Page Not Found',
  NOT_FOUND_DESCRIPTION: 'The page you are looking for does not exist.',
  NOT_FOUND_HOME: 'Go Home',

  SHORTCUT_OVERLAY_TITLE: 'Keyboard Shortcuts',
  SHORTCUT_CATEGORY_GLOBAL: 'Global',
  SHORTCUT_CATEGORY_NAVIGATION: 'Navigation',
  SHORTCUT_CATEGORY_ANIMATION: 'Animation',

  PERFORMANCE_COMPOSITE: 'Composite',
  PERFORMANCE_PAINT: 'Paint',
  PERFORMANCE_LAYOUT: 'Layout',
  PERFORMANCE_FIX: 'Fix it',
  PERFORMANCE_SUGGESTIONS: 'Optimization Suggestions',

  REORDER_MODE: 'Reorder Mode',
  REORDER_RESET: 'Reset Order',

  INSTALL_APP: 'Install App',
  OFFLINE_BANNER: 'You are currently offline. Some features may be unavailable.',
}
